# **Project Name**    - **Entertainer Data Analysis**

![hand-drawn-doodle-movie-cinema-set_88138-1050.avif]()

# **Project Summary -**

This project aims to conduct Data Analysis on a dataset containing information about various entertainers, including musicians, actors, and television personalities. The dataset includes details such as the year of breakthrough, major works, awards nominations, gender, birth year, and year of death (if applicable) for each entertainer. By analyzing this dataset, we seek to uncover patterns, trends, and insights into the careers of these entertainers, identifying factors that contribute to their success and longevity in the entertainment industry.

### Import Libraries

In [ ]:
#import all library that will be used in entire project
import numpy as np                               #importing numpy
import pandas as pd                              #imporing pandas
import matplotlib.pyplot as plt                  #imporitng matplotlib
import seaborn as sns                            #importing seaborn

### Dataset Loading

In [ ]:
#Mount google drive for access the dataset of Entertainer
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#File path of Entertainer dataset in google drive
file_path = "/content/drive/MyDrive/Entertainer Data Analytics_DataSet/Entertainer-Basic-Info.csv"
BasicInfo_df = pd.read_csv(file_path)

In [ ]:
file_path = "/content/drive/MyDrive/Entertainer Data Analytics_DataSet/Entertainer-Breakthrough-Info.csv"
BreakthroughInfo_df = pd.read_csv(file_path)

In [ ]:
file_path = "/content/drive/MyDrive/Entertainer Data Analytics_DataSet/Entertainer-Last-work-Info.csv"
LastWorkInfo_df = pd.read_csv(file_path)

In [ ]:
file_path = "/content/drive/MyDrive/imdb_top_1000.csv"
Imdb_df = pd.read_csv(file_path)

### Dataset First View

In [ ]:
BasicInfo_df.head()

       Entertainer Gender (traditional)  Birth Year
0            Adele                    F        1988
1   Angelina Jolie                    F        1975
2  Aretha Franklin                    F        1942
3      Bette Davis                    F        1908
4      Betty White                    F        1922

In [ ]:
BreakthroughInfo_df.head()

,Entertainer,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy
0,Adele,2008,19,2009.0
1,Angelina Jolie,1999,"Girl, Interrupted",1999.0
2,Aretha Franklin,1967,I Never Loved a Man (The Way I Love You),1968.0
3,Bette Davis,1934,Of Human Bondage,1935.0
4,Betty White,1952,Life with Elilzabeth,1976.0

In [ ]:
LastWorkInfo_df.head()

       Entertainer  Year of Last Major Work (arguable)  Year of Death
0            Adele                                2016            NaN
1   Angelina Jolie                                2016            NaN
2  Aretha Franklin                                2014            NaN
3      Bette Davis                                1989         1989.0
4      Betty White                                2016            NaN

In [ ]:
Imdb_df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
# Selecting specific columns from the IMDb dataset
selected_columns = ['Runtime', 'Genre', 'IMDB_Rating', 'Meta_score', 'Gross', 'Director']
Imdb_df = Imdb_df[selected_columns]

Now let's join all the DataSet based on columns.

In [ ]:
# Assuming BasicInfo_df, BreakthroughInfo_df, and LastWorkInfo_df are your existing DataFrames
# Assuming Imdb_df contains IMDb data
# Merging the data based on common data set for IMDB data

# Merge IMDb data with BasicInfo_df using 'inner' join
Final_data = pd.merge(BasicInfo_df, Imdb_df, left_index=True, right_index=True, how='inner')

# Merge with BreakthroughInfo_df using 'inner' join
Final_data = pd.merge(Final_data, BreakthroughInfo_df, left_index=True, right_index=True, how='inner')

# Merge with LastWorkInfo_df using 'inner' join
Final_data = pd.merge(Final_data, LastWorkInfo_df, left_index=True, right_index=True, how='inner')

# Print or inspect merged_data to verify the merged DataFrame
Final_data

,Entertainer_x,Gender (traditional),Birth Year,Runtime,Genre,IMDB_Rating,Meta_score,Gross,Director,Entertainer_y,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Entertainer,Year of Last Major Work (arguable),Year of Death
0,Adele,F,1988,142 min,Drama,9.3,80.0,"28,341,469",Frank Darabont,Adele,2008,19,2009.0,Adele,2016,NaN
1,Angelina Jolie,F,1975,175 min,"Crime, Drama",9.2,100.0,"134,966,411",Francis Ford Coppola,Angelina Jolie,1999,"Girl, Interrupted",1999.0,Angelina Jolie,2016,NaN
2,Aretha Franklin,F,1942,152 min,"Action, Crime, Drama",9.0,84.0,"534,858,444",Christopher Nolan,Aretha Franklin,1967,I Never Loved a Man (The Way I Love You),1968.0,Aretha Franklin,2014,NaN
3,Bette Davis,F,1908,202 min,"Crime, Drama",9.0,90.0,"57,300,000",Francis Ford Coppola,Bette Davis,1934,Of Human Bondage,1935.0,Bette Davis,1989,1989.0
4,Betty White,F,1922,96 min,"Crime, Drama",9.0,96.0,"4,360,000",Sidney Lumet,Betty White,1952,Life with Elilzabeth,1976.0,Betty White,2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Tom Hanks,M,1956,165 min,"Drama, Family",8.4,NaN,"1,223,869",Aamir Khan,Tom Hanks,1984,Splash,1993.0,Tom Hanks,2016,NaN
66,Tony Bennett,M,1926,98 min,"Animation, Adventure, Family",8.4,95.0,"223,808,164",Andrew Stanton,Tony Bennett,1951,Because of You,1963.0,Tony Bennett,2016,NaN
67,Wayne Newton,M,1942,137 min,"Drama, Mystery, Thriller",8.4,89.0,"11,286,112",Florian Henckel von Donnersmarck,Wayne Newton,1972,"Daddy, Don't You Walk So Fast",NaN,Wayne Newton,2016,NaN
68,Will Smith,M,1968,101 min,"Action, Drama, Mystery",8.4,77.0,"707,481",Chan-wook Park,Will Smith,1990,The Fresh Prince of Bel-Air,1988.0,Will Smith,2016,NaN
69,Willie Nelson,M,1933,113 min,"Mystery, Thriller",8.4,80.0,"25,544,867",Christopher Nolan,Willie Nelson,1975,Red Headed Stranger,1976.0,Willie Nelson,2016,NaN

In [ ]:
Final_data.head()

,Entertainer_x,Gender (traditional),Birth Year,Runtime,Genre,IMDB_Rating,Meta_score,Gross,Director,Entertainer_y,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Entertainer,Year of Last Major Work (arguable),Year of Death
0,Adele,F,1988,142 min,Drama,9.3,80.0,"28,341,469",Frank Darabont,Adele,2008,19,2009.0,Adele,2016,NaN
1,Angelina Jolie,F,1975,175 min,"Crime, Drama",9.2,100.0,"134,966,411",Francis Ford Coppola,Angelina Jolie,1999,"Girl, Interrupted",1999.0,Angelina Jolie,2016,NaN
2,Aretha Franklin,F,1942,152 min,"Action, Crime, Drama",9.0,84.0,"534,858,444",Christopher Nolan,Aretha Franklin,1967,I Never Loved a Man (The Way I Love You),1968.0,Aretha Franklin,2014,NaN
3,Bette Davis,F,1908,202 min,"Crime, Drama",9.0,90.0,"57,300,000",Francis Ford Coppola,Bette Davis,1934,Of Human Bondage,1935.0,Bette Davis,1989,1989.0
4,Betty White,F,1922,96 min,"Crime, Drama",9.0,96.0,"4,360,000",Sidney Lumet,Betty White,1952,Life with Elilzabeth,1976.0,Betty White,2016,NaN

Droping Duplicate Columns

In [ ]:
# Drop additional columns in the code
Final_data.drop(['Entertainer','Entertainer_y'], axis = 1, inplace = True)
Final_data = Final_data.rename(columns ={'Entertainer_x': 'Entertainer'})

In [ ]:
Final_data.head()

,Entertainer,Gender (traditional),Birth Year,Runtime,Genre,IMDB_Rating,Meta_score,Gross,Director,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death
0,Adele,F,1988,142 min,Drama,9.3,80.0,"28,341,469",Frank Darabont,2008,19,2009.0,2016,NaN
1,Angelina Jolie,F,1975,175 min,"Crime, Drama",9.2,100.0,"134,966,411",Francis Ford Coppola,1999,"Girl, Interrupted",1999.0,2016,NaN
2,Aretha Franklin,F,1942,152 min,"Action, Crime, Drama",9.0,84.0,"534,858,444",Christopher Nolan,1967,I Never Loved a Man (The Way I Love You),1968.0,2014,NaN
3,Bette Davis,F,1908,202 min,"Crime, Drama",9.0,90.0,"57,300,000",Francis Ford Coppola,1934,Of Human Bondage,1935.0,1989,1989.0
4,Betty White,F,1922,96 min,"Crime, Drama",9.0,96.0,"4,360,000",Sidney Lumet,1952,Life with Elilzabeth,1976.0,2016,NaN

Missing values/Null values

In [ ]:
#Checking the missing / Null values
Final_data.isnull().sum()

Entertainer                                      0
Gender (traditional)                             0
Birth Year                                       0
Runtime                                          0
Genre                                            0
IMDB_Rating                                      0
Meta_score                                       5
Gross                                            7
Director                                         0
Year of Breakthrough/#1 Hit/Award Nomination     0
Breakthrough Name                                0
Year of First Oscar/Grammy/Emmy                  6
Year of Last Major Work (arguable)               0
Year of Death                                   40
dtype: int64

After observing the Data set we can say there are 6 missing data in the Year of First Oscar/Grammy/Emmy, 40 missing data in the column Year of Death, 5 missing data from the column Meta_score and 7 from Gross column.

Firstly converting the decimal type number into proper interger fomat, from the given columns Year of First Oscar/ Grammy / Emmy awards and Year of Death.

In [ ]:
#Convert columns to integers
Final_data['Year of First Oscar/Grammy/Emmy'] = Final_data['Year of First Oscar/Grammy/Emmy'].astype(float).astype('Int64')
Final_data['Year of Death'] = Final_data['Year of Death'].astype(float).astype('Int64')

Replacing the Null / Missing values with some content

In [ ]:
Final_data['Year of First Oscar/Grammy/Emmy'] = Final_data['Year of First Oscar/Grammy/Emmy'].astype('object')
Final_data['Year of Death'] = Final_data['Year of Death'].astype('object')

#Filling the missing/null data with some content.
Final_data.fillna({'Year of First Oscar/Grammy/Emmy': 'Not Available', 'Year of Death': 'Alive', 'Meta_score': 'Not available', 'Gross': 0}, inplace=True)

In [ ]:
#Again checking for null values
Final_data.isnull().sum()

Entertainer                                     0
Gender (traditional)                            0
Birth Year                                      0
Runtime                                         0
Genre                                           0
IMDB_Rating                                     0
Meta_score                                      0
Gross                                           0
Director                                        0
Year of Breakthrough/#1 Hit/Award Nomination    0
Breakthrough Name                               0
Year of First Oscar/Grammy/Emmy                 0
Year of Last Major Work (arguable)              0
Year of Death                                   0
dtype: int64

In [ ]:
#Dataset Info and check how many entries are there left after cleaning the data
Final_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 0 to 69
Data columns (total 14 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Entertainer                                   70 non-null     object
 1   Gender (traditional)                          70 non-null     object
 2   Birth Year                                    70 non-null     int64
 3   Runtime                                       70 non-null     object
 4   Genre                                         70 non-null     object
 5   IMDB_Rating                                   70 non-null     float64
 6   Meta_score                                    70 non-null     object
 7   Gross                                         70 non-null     object
 8   Director                                      70 non-null     object
 9   Year of Breakthrough/#1 Hit/Award Nomination  70 non-null     int64
 10  Breakthrough Name                             70 non-null     object
 11  Year of First Oscar/Grammy/Emmy               70 non-null     object
 12  Year of Last Major Work (arguable)            70 non-null     int64
 13  Year of Death                                 70 non-null     object
dtypes: float64(1), int64(3), object(10)
memory usage: 10.3+ KB

In [ ]:
#Counting the number of rows and column after cleaning the data set
row, columns = Final_data.shape
print(f"No of rows: {row}")
print(f"No of columns: {columns}")

No of rows: 70
No of columns: 14

In [ ]:
#Data set view after cleaning
Final_data.head()

,Entertainer,Gender (traditional),Birth Year,Runtime,Genre,IMDB_Rating,Meta_score,Gross,Director,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death
0,Adele,F,1988,142 min,Drama,9.3,80.0,"28,341,469",Frank Darabont,2008,19,2009,2016,Alive
1,Angelina Jolie,F,1975,175 min,"Crime, Drama",9.2,100.0,"134,966,411",Francis Ford Coppola,1999,"Girl, Interrupted",1999,2016,Alive
2,Aretha Franklin,F,1942,152 min,"Action, Crime, Drama",9.0,84.0,"534,858,444",Christopher Nolan,1967,I Never Loved a Man (The Way I Love You),1968,2014,Alive
3,Bette Davis,F,1908,202 min,"Crime, Drama",9.0,90.0,"57,300,000",Francis Ford Coppola,1934,Of Human Bondage,1935,1989,1989
4,Betty White,F,1922,96 min,"Crime, Drama",9.0,96.0,"4,360,000",Sidney Lumet,1952,Life with Elilzabeth,1976,2016,Alive

This much Data are not enough to do the analysis. So, I have downloaded more data from IMDB data set Universal library.

In [ ]:
!pip install imdbpy
!pip install openpyxl
import imdb
mi = imdb.Cinemagoer()

Collecting imdbpy
  Downloading IMDbPY-2022.7.9-py3-none-any.whl (1.2 kB)
Collecting cinemagoer (from imdbpy)
  Downloading cinemagoer-2023.5.1-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.2/297.2 kB 5.4 MB/s eta 0:00:00
Requirement already satisfied: SQLAlchemy in /usr/local/lib/python3.10/dist-packages (from cinemagoer->imdbpy) (2.0.30)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from cinemagoer->imdbpy) (4.9.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy->cinemagoer->imdbpy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy->cinemagoer->imdbpy) (3.0.3)
Installing collected packages: cinemagoer, imdbpy
Successfully installed cinemagoer-2023.5.1 imdbpy-2022.7.9
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

Creating lists to store the extracted data of Persons like number of films act, height, quotes, pics from IMDB data set.

In [ ]:
pics = []
num_films_act = []
quotes = []
height = []

for i in range(len(BasicInfo_df)):
    ent_name = BasicInfo_df.Entertainer[i]
    print("Starting-->", ent_name)
    people = mi.search_person(ent_name)
    if len(people):
        try:
            per = mi.get_person(people[0].personID)
        except:
            per = people[0]

        keys = per.keys()

        #Picture of the person
        if "full-size headshot" in keys:
            pics.append(per["full-size headshot"])
        elif "headshot" in keys:
            pics.append(per["headshot"])
        else:
            pics.append("NA")

        #count of flims acted
        if "filmography" in keys:
            if "actor" in per["filmography"]:
                num_films_act.append(len(per["filmography"]["actor"]))
            elif "actress" in per["filmography"]:
                num_films_act.append(len(per["filmography"]["actress"]))
            else:
                num_films_act.append(0)
        else:
            num_films_act.append(0)

        #height
        if "height" in keys:
            height.append(per["height"])
        else:
            height.append("NA")

        #Quotes
        if "quotes" in keys:
            quotes.append(per["quotes"][0])
        else:
            quotes.append("NA")
    else:
        height.append("Np")
        pics.append("Np")
        num_films_act.append("Np")
        quotes.append("Np")

    print("Done----->", ent_name)
    print("    ")

Done-----> Justin Timberlake

Starting--> Katherine Hepburn
Done-----> Katherine Hepburn

Starting--> Keifer Sutherland
Done-----> Keifer Sutherland

Starting--> Kirk Douglas
Done-----> Kirk Douglas

Starting--> Lady Gaga
Done-----> Lady Gaga

Starting--> Leonard Bernstein
Done-----> Leonard Bernstein

Starting--> Leonardo DiCaprio
Done-----> Leonardo DiCaprio

Starting--> Louis Armstrong
Done-----> Louis Armstrong

Starting--> Madonna
Done-----> Madonna

Starting--> Mariah Carey
Done-----> Mariah Carey

Starting--> Marlon Brando
Done-----> Marlon Brando

Starting--> Mary Tyler Moore
Done-----> Mary Tyler Moore

Starting--> Meryl Streep
Done-----> Meryl Streep

Starting--> Mick Jagger
Done-----> Mick Jagger

Starting--> Morgan Freeman
Done-----> Morgan Freeman

Starting--> Oprah Winfrey

2024-05-10 15:17:12,908 CRITICAL [imdbpy] /usr/local/lib/python3.10/dist-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0001856/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
CRITICAL:imdbpy:IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0001856/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
2024-05-10 15:17:12,911 CRITICAL [imdbpy] /usr/local/lib/python3.10/dist-packages/imdb/__init__.py:850: caught an exception retrieving or parsing "filmography" info set for mopID "0001856" (accessSystem: http)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 702, in get_person_filmography
    cont = self._retrieve(self.urls['person_main'] % personID + 'fullcredits')
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 392, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 261, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0001856/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')}
CRITICAL:imdbpy:caught an exception retrieving or parsing "filmography" info set for mopID "0001856" (accessSystem: http)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 702, in get_person_filmography
    cont = self._retrieve(self.urls['person_main'] % personID + 'fullcredits')
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 392, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 261, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0001856/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')}

Done-----> Oprah Winfrey

Starting--> Paul McCartney

2024-05-10 15:17:45,624 CRITICAL [imdbpy] /usr/local/lib/python3.10/dist-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0005200/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
CRITICAL:imdbpy:IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0005200/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
2024-05-10 15:17:45,628 CRITICAL [imdbpy] /usr/local/lib/python3.10/dist-packages/imdb/__init__.py:850: caught an exception retrieving or parsing "filmography" info set for mopID "0005200" (accessSystem: http)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 702, in get_person_filmography
    cont = self._retrieve(self.urls['person_main'] % personID + 'fullcredits')
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 392, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 261, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0005200/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')}
CRITICAL:imdbpy:caught an exception retrieving or parsing "filmography" info set for mopID "0005200" (accessSystem: http)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 702, in get_person_filmography
    cont = self._retrieve(self.urls['person_main'] % personID + 'fullcredits')
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 392, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py", line 261, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/name/nm0005200/fullcredits', 'proxy': '', 'exception type': 'IOError', 'original exception': TimeoutError('The read operation timed out')}

Done-----> Paul McCartney

Starting--> Paul Newman
Done-----> Paul Newman

Starting--> Peter O'Toole
Done-----> Peter O'Toole

Starting--> Prince
Done-----> Prince

Starting--> Robert Redford
Done-----> Robert Redford

Starting--> Sidney Poitier
Done-----> Sidney Poitier

Starting--> Sly Stone
Done-----> Sly Stone

Starting--> Stevie Wonder
Done-----> Stevie Wonder

Starting--> Tom Hanks
Done-----> Tom Hanks

Starting--> Tony Bennett
Done-----> Tony Bennett

Starting--> Wayne Newton
Done-----> Wayne Newton

Starting--> Will Smith
Done-----> Will Smith

Starting--> Willie Nelson
Done-----> Willie Nelson

In [ ]:
#Checking the data length
print(len(pics))
print(len(height))
print(len(num_films_act))
print(len(quotes))

70
70
70
70

In [ ]:
#Adding the extracted data to the final data set
Final_data["Picture"] = pics
Final_data["Height"] = height
Final_data["Number_films_act"] = num_films_act
Final_data["Quote"] = quotes

In [ ]:
Final_data

,Entertainer,Gender (traditional),Birth Year,Runtime,Genre,IMDB_Rating,Meta_score,Gross,Director,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death,Picture,Height,Number_films_act,Quote
0,Adele,F,1988,142 min,Drama,9.3,80.0,"28,341,469",Frank Darabont,2008,19,2009,2016,Alive,https://m.media-amazon.com/images/M/MV5BZmU3MT...,NA,99,NA
1,Angelina Jolie,F,1975,175 min,"Crime, Drama",9.2,100.0,"134,966,411",Francis Ford Coppola,1999,"Girl, Interrupted",1999,2016,Alive,https://m.media-amazon.com/images/M/MV5BODg3Mz...,NA,66,NA
2,Aretha Franklin,F,1942,152 min,"Action, Crime, Drama",9.0,84.0,"534,858,444",Christopher Nolan,1967,I Never Loved a Man (The Way I Love You),1968,2014,Alive,https://m.media-amazon.com/images/M/MV5BNjc1OD...,NA,22,NA
3,Bette Davis,F,1908,202 min,"Crime, Drama",9.0,90.0,"57,300,000",Francis Ford Coppola,1934,Of Human Bondage,1935,1989,1989,https://m.media-amazon.com/images/M/MV5BZmMzMj...,NA,124,NA
4,Betty White,F,1922,96 min,"Crime, Drama",9.0,96.0,"4,360,000",Sidney Lumet,1952,Life with Elilzabeth,1976,2016,Alive,https://m.media-amazon.com/images/M/MV5BMjA2OT...,NA,130,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Tom Hanks,M,1956,165 min,"Drama, Family",8.4,Not available,"1,223,869",Aamir Khan,1984,Splash,1993,2016,Alive,https://m.media-amazon.com/images/M/MV5BMTQ2Mj...,NA,98,NA
66,Tony Bennett,M,1926,98 min,"Animation, Adventure, Family",8.4,95.0,"223,808,164",Andrew Stanton,1951,Because of You,1963,2016,Alive,https://m.media-amazon.com/images/M/MV5BMTIwNj...,NA,33,NA
67,Wayne Newton,M,1942,137 min,"Drama, Mystery, Thriller",8.4,89.0,"11,286,112",Florian Henckel von Donnersmarck,1972,"Daddy, Don't You Walk So Fast",Not Available,2016,Alive,https://m.media-amazon.com/images/M/MV5BMTQzNT...,NA,49,NA
68,Will Smith,M,1968,101 min,"Action, Drama, Mystery",8.4,77.0,"707,481",Chan-wook Park,1990,The Fresh Prince of Bel-Air,1988,2016,Alive,https://m.media-amazon.com/images/M/MV5BNTczMz...,NA,92,NA
69,Willie Nelson,M,1933,113 min,"Mystery, Thriller",8.4,80.0,"25,544,867",Christopher Nolan,1975,Red Headed Stranger,1976,2016,Alive,https://m.media-amazon.com/images/M/MV5BMjA5NT...,NA,138,NA

In [ ]:
#After finding that height and Quote column have no data so I drop the columns
Final_data.drop(['Height', 'Quote'], axis=1, inplace=True)

In [ ]:
Final_data.head()

,Entertainer,Gender (traditional),Birth Year,Runtime,Genre,IMDB_Rating,Meta_score,Gross,Director,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death,Picture,Number_films_act
0,Adele,F,1988,142 min,Drama,9.3,80.0,"28,341,469",Frank Darabont,2008,19,2009,2016,Alive,https://m.media-amazon.com/images/M/MV5BZmU3MT...,99
1,Angelina Jolie,F,1975,175 min,"Crime, Drama",9.2,100.0,"134,966,411",Francis Ford Coppola,1999,"Girl, Interrupted",1999,2016,Alive,https://m.media-amazon.com/images/M/MV5BODg3Mz...,66
2,Aretha Franklin,F,1942,152 min,"Action, Crime, Drama",9.0,84.0,"534,858,444",Christopher Nolan,1967,I Never Loved a Man (The Way I Love You),1968,2014,Alive,https://m.media-amazon.com/images/M/MV5BNjc1OD...,22
3,Bette Davis,F,1908,202 min,"Crime, Drama",9.0,90.0,"57,300,000",Francis Ford Coppola,1934,Of Human Bondage,1935,1989,1989,https://m.media-amazon.com/images/M/MV5BZmMzMj...,124
4,Betty White,F,1922,96 min,"Crime, Drama",9.0,96.0,"4,360,000",Sidney Lumet,1952,Life with Elilzabeth,1976,2016,Alive,https://m.media-amazon.com/images/M/MV5BMjA2OT...,130

###After cleaning the data and handling missing values, the final DataFrame **Final_data** was converted into a CSV file for further analysis.

In [ ]:
Final_data.to_csv('Final_Entertainer_data.csv')

Create a different CSV file for actor and actress names, movies names and publish year of movies for all the actor and actress.

In [ ]:
#List for actor names, movies and publish year of the movies
actor = []
movie_title = []
year = []

#Function to get all the actor and actress name, movies done and movie publish year from IMDB
for i in range(len(BasicInfo_df)):
    ent_name = BasicInfo_df.Entertainer[i]
    leen = len(movie_title)
    print("Start-->", ent_name)
    persons = mi.search_person(ent_name)
    try:
        per = mi.get_person(persons[0].personID)
        if 'filmography' in per.keys():
            ma_keys = per["filmography"].keys()
            if "actor" in ma_keys:
                act = per["filmography"]["actor"]

                for j in range(len(act)):
                    movi = mi.get_movie(act[j].movieID)
                    k = movi.keys()
                    actor.append(ent_name)
                    if "title" in k:
                        movie_title.append(movi["title"])
                    else:
                        movie_title.append("NA")

                    if "year" in k:
                        year.append(movi["year"])
                    else:
                        year.append("NA")

            elif "actress" in  ma_keys:
                act = per["filmography"]["actress"]

                for j in range(len(act)):
                    movi = mi.get_movie(act[j].movieID)
                    k = movi.keys()
                    actor.append(ent_name)
                    if "title" in k:
                        movie_title.append(movi["title"])
                    else:
                        movie_title.append("NA")

                    if "year" in k:
                        year.append(movi["year"])
                    else:
                        year.append("NA")
            else:
                actor.append(ent_name)
                movie_title.append("NA")
                year.append("NA")
        else:
            actor.append(ent_name)
            movie_title.append("NA")
            year.append("NA")
    except:
        actor.append(ent_name)
        movie_title.append("NA")
        year.append("NA")
    print("Done-->", ent_name, " Added--> ", len(movie_title)-leen, " Movies")
    print("   ")

Done--> Paul Newman  Added-->  84  Movies

Start--> Peter O'Toole
Done--> Peter O'Toole  Added-->  102  Movies

Start--> Prince
Done--> Prince  Added-->  81  Movies

Start--> Robert Redford
Done--> Robert Redford  Added-->  83  Movies

Start--> Sidney Poitier
Done--> Sidney Poitier  Added-->  57  Movies

Start--> Sly Stone
Done--> Sly Stone  Added-->  1  Movies

Start--> Stevie Wonder
Done--> Stevie Wonder  Added-->  34  Movies

Start--> Tom Hanks
Done--> Tom Hanks  Added-->  98  Movies

Start--> Tony Bennett
Done--> Tony Bennett  Added-->  33  Movies

Start--> Wayne Newton
Done--> Wayne Newton  Added-->  49  Movies

Start--> Will Smith
Done--> Will Smith  Added-->  92  Movies

Start--> Willie Nelson
Done--> Willie Nelson  Added-->  138  Movies

In [ ]:
#Checking the data length
print(len(actor))
print(len(movie_title))
print(len(year))

4879
4879
4879

In [ ]:
#Convert the list into a proper Dataframe format
Actors_films_list_df = pd.DataFrame({"Actor Name":actor, "Movie Title":movie_title, " Year of Publish":year})

Convert the final data set of actor names and movies publish year to CSV file.

In [ ]:
Actors_films_list_df.to_csv("Actors_films_list.csv")

Collection of Number of awards received, nominated actor and Oscars award received.

##**Conclusion**

The data processing workflow undertaken effectively addressed several key aspects of data management and enrichment.

* Data Cleaning: Duplicate columns were successfully identified and removed, ensuring data integrity and eliminating redundancy. Unwanted columns such as 'Height' and 'Quote' were dropped, streamlining the dataset for further analysis.

* Data Type Conversion: The conversion of data types, particularly for 'Year of First Oscar/Grammy/Emmy' and 'Year of Death', was pivotal for ensuring uniformity and facilitating numerical operations on these fields.

* Error Handling and Data Enrichment: Despite encountering challenges during the enrichment process, efforts were made to retrieve additional information such as movie director names from IMDb. However, unforeseen issues like connectivity problems and missing data hindered the complete execution of this task.

* Handling Missing Values: Missing values were appropriately handled by replacing them with meaningful placeholders like 'Not Available', ensuring that the dataset remains informative and comprehensive.

* Next Steps: Moving forward, there is an opportunity to explore alternative data sources or refine the data retrieval process to overcome the challenges encountered during data enrichment. Additionally, further analysis could be conducted to extract valuable insights from the enriched dataset, potentially uncovering hidden patterns or correlations.